2025-03-16 01:04:09,310 - InstagramBot - INFO - Logging in with username and password
2025-03-16 01:04:09,310 - instagrapi - INFO - https://i.instagram.com/api/v1/launcher/sync/
2025-03-16 01:04:09,635 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/launcher/sync/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:04:09,829 - instagrapi - INFO - https://i.instagram.com/api/v1/accounts/login/
2025-03-16 01:04:18,245 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/accounts/login/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:04:19,246 - instagrapi - INFO - https://i.instagram.com/api/v1/feed/reels_tray/
2025-03-16 01:04:19,994 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/feed/reels_tray/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:04:20,997 - instagrapi - INFO - https://i.instagram.com/api/v1/feed/timeline/
2025-03-16 01:04:23,188 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/feed/timeline/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:04:23,193 - InstagramBot - INFO - Successfully logged in as veltric_solutions
2025-03-16 01:04:23,193 - InstagramBot - INFO - Starting to unfollow users who don't follow you back
2025-03-16 01:04:24,194 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/72847825264/following/
2025-03-16 01:04:24,807 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/friendships/72847825264/following/?max_id=&count=200&rank_token=72847825264_91e7cdb6-eac8-4128-8c3c-660493535bc7&search_surface=follow_list_page&query=&enable_groups=true (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:04:24,812 - InstagramBot - INFO - You are following 72 users
2025-03-16 01:04:26,381 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%2272847825264%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%7D&query_hash=37479f2b8209594dde7facb0d904896a
2025-03-16 01:04:28,775 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%2272847825264%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%2C%22after%22%3A%22QVFBYXhuaEdLVHJVNWFoV0lCQkdVelU2d0Qycm9PV1o4MXpTOWQxSHN2UTZHMEVJVlJQUjhsS0lsbDJPS2U1WmdHSV9qazRsOEZTRU14S0VVS2dRMmJDZg%3D%3D%22%7D&query_hash=37479f2b8209594dde7facb0d904896a
2025-03-16 01:04:31,030 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%2272847825264%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%2C%22after%22%3A%22QVFEaUpSWFFOMDJBSmNVZmhVZDU4UDFzdUlKVFVmNDVmRENIeDVRXzQ2ajNpMmc4OFJaT3dZRjNmWjIyUHFTR3pEbXlKMTk5TjRrcmFPdjBTVmg3WC1QcQ%3D%3D%22%7D&query_hash=37479f2b8209594dde7facb0d904896a
2025-03-16 01:04:31,030 - InstagramBot - INFO - You have 30 followers
2025-03-16 01:04:31,030 - InstagramBot - INFO - Found 55 users who don't follow you back
2025-03-16 01:04:32,031 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/46576481771/
2025-03-16 01:04:33,306 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/46576481771/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:04:33,307 - InstagramBot - INFO - Unfollowed marzomall
2025-03-16 01:04:33,307 - InstagramBot - INFO - Waiting 25.85 seconds before next unfollow
2025-03-16 01:05:00,157 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/48736471543/
2025-03-16 01:05:02,797 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/48736471543/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:05:02,797 - InstagramBot - INFO - Unfollowed princess.accessories.dr
2025-03-16 01:05:02,797 - InstagramBot - INFO - Waiting 23.96 seconds before next unfollow
2025-03-16 01:05:27,761 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/3189982068/
2025-03-16 01:05:28,908 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/3189982068/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:05:28,909 - InstagramBot - INFO - Unfollowed ladiesempireshop
2025-03-16 01:05:28,909 - InstagramBot - INFO - Waiting 19.58 seconds before next unfollow
2025-03-16 01:05:49,486 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/34160166958/
2025-03-16 01:05:50,516 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/34160166958/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:05:50,516 - InstagramBot - INFO - Unfollowed keriloocandles
2025-03-16 01:05:50,516 - InstagramBot - INFO - Waiting 25.69 seconds before next unfollow
2025-03-16 01:06:17,208 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/59097033241/
2025-03-16 01:06:18,368 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/59097033241/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:06:18,369 - InstagramBot - INFO - Unfollowed glamorise__branduk
2025-03-16 01:06:18,369 - InstagramBot - INFO - Waiting 29.59 seconds before next unfollow
2025-03-16 01:06:48,963 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/1510977005/
2025-03-16 01:06:50,103 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/1510977005/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:06:50,103 - InstagramBot - INFO - Unfollowed anis.butik
2025-03-16 01:06:50,103 - InstagramBot - INFO - Waiting 17.79 seconds before next unfollow
2025-03-16 01:07:08,896 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/5629132419/
2025-03-16 01:07:09,897 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/5629132419/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:07:09,897 - InstagramBot - INFO - Unfollowed butiku_jone1
2025-03-16 01:07:09,898 - InstagramBot - INFO - Waiting 27.77 seconds before next unfollow
2025-03-16 01:07:38,667 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/4193710221/
2025-03-16 01:07:39,571 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/4193710221/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:07:39,572 - InstagramBot - INFO - Unfollowed butiku_akcion
2025-03-16 01:07:39,572 - InstagramBot - INFO - Waiting 24.34 seconds before next unfollow
2025-03-16 01:08:04,915 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/destroy/51747572112/
2025-03-16 01:08:05,889 - private_request - INFO - veltric_solutions [200] POST https://i.instagram.com/api/v1/friendships/destroy/51747572112/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:08:05,889 - InstagramBot - INFO - Unfollowed bohotique_fashion
2025-03-16 01:08:05,889 - InstagramBot - INFO - Waiting 29.89 seconds before next unfollow
2025-03-16 01:12:46,548 - InstagramBot - INFO - Loading session from file
2025-03-16 01:12:46,548 - InstagramBot - INFO - Successfully logged in as veltric_solutions
2025-03-16 01:12:46,549 - InstagramBot - INFO - Starting to unfollow users who don't follow you back
2025-03-16 01:12:47,549 - instagrapi - INFO - https://i.instagram.com/api/v1/friendships/72847825264/following/
2025-03-16 01:12:48,327 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/friendships/72847825264/following/?max_id=&count=200&rank_token=72847825264_91e7cdb6-eac8-4128-8c3c-660493535bc7&search_surface=follow_list_page&query=&enable_groups=true (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:12:48,329 - InstagramBot - INFO - You are following 63 users
2025-03-16 01:14:40,269 - InstagramBot - INFO - Loading session from file
2025-03-16 01:14:40,270 - InstagramBot - INFO - Successfully logged in as veltric_solutions
2025-03-16 01:14:40,270 - InstagramBot - INFO - Starting to follow followers of albiidr18
2025-03-16 01:14:41,650 - public_request - INFO - [None] [201] GET https://www.instagram.com/albiidr18/?__a=1&__d=dis
2025-03-16 01:14:41,651 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/albiidr18/?__a=1&__d=dis) >>> 
2025-03-16 01:14:44,797 - public_request - INFO - [None] [201] GET https://www.instagram.com/albiidr18/?__a=1&__d=dis
2025-03-16 01:14:44,798 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/albiidr18/?__a=1&__d=dis) >>> 
2025-03-16 01:14:47,931 - public_request - INFO - [None] [201] GET https://www.instagram.com/albiidr18/?__a=1&__d=dis
2025-03-16 01:14:47,931 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/albiidr18/?__a=1&__d=dis) >>> 
2025-03-16 01:14:48,933 - instagrapi - INFO - https://i.instagram.com/api/v1/users/albiidr18/usernameinfo/
2025-03-16 01:14:49,338 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/albiidr18/usernameinfo/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:14:49,339 - InstagramBot - INFO - Getting followers for user: albiidr18 (ID: 60628317391)
2025-03-16 01:14:50,740 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%2260628317391%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%7D&query_hash=37479f2b8209594dde7facb0d904896a
2025-03-16 01:14:50,741 - InstagramBot - INFO - Found 10 followers
2025-03-16 01:14:50,741 - InstagramBot - ERROR - Error in follow_user_followers: 'Client' object has no attribute 'user_friendship'
2025-03-16 01:15:18,914 - InstagramBot - INFO - Loading session from file
2025-03-16 01:15:18,915 - InstagramBot - INFO - Successfully logged in as veltric_solutions
2025-03-16 01:15:18,915 - InstagramBot - INFO - Starting to follow followers of jerakullolli
2025-03-16 01:15:20,103 - public_request - INFO - [None] [201] GET https://www.instagram.com/jerakullolli/?__a=1&__d=dis
2025-03-16 01:15:20,103 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jerakullolli/?__a=1&__d=dis) >>> 
2025-03-16 01:15:23,263 - public_request - INFO - [None] [201] GET https://www.instagram.com/jerakullolli/?__a=1&__d=dis
2025-03-16 01:15:23,263 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jerakullolli/?__a=1&__d=dis) >>> 
2025-03-16 01:15:26,367 - public_request - INFO - [None] [201] GET https://www.instagram.com/jerakullolli/?__a=1&__d=dis
2025-03-16 01:15:26,368 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jerakullolli/?__a=1&__d=dis) >>> 
2025-03-16 01:15:27,368 - instagrapi - INFO - https://i.instagram.com/api/v1/users/jerakullolli/usernameinfo/
2025-03-16 01:15:27,866 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/jerakullolli/usernameinfo/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:15:27,868 - InstagramBot - INFO - Getting followers for user: jerakullolli (ID: 58970943510)
2025-03-16 01:15:29,254 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%2258970943510%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%7D&query_hash=37479f2b8209594dde7facb0d904896a
2025-03-16 01:15:29,255 - InstagramBot - INFO - Found 10 followers
2025-03-16 01:15:29,255 - InstagramBot - ERROR - Error in follow_user_followers: 'Client' object has no attribute 'user_friendship'
2025-03-16 01:17:25,497 - InstagramBot - INFO - Loading session from file
2025-03-16 01:17:25,498 - InstagramBot - INFO - Successfully logged in as veltric_solutions
2025-03-16 01:17:25,498 - InstagramBot - INFO - Starting to follow followers of jerakullolli
2025-03-16 01:17:26,703 - public_request - INFO - [None] [201] GET https://www.instagram.com/jerakullolli/?__a=1&__d=dis
2025-03-16 01:17:26,704 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jerakullolli/?__a=1&__d=dis) >>> 
2025-03-16 01:17:29,843 - public_request - INFO - [None] [201] GET https://www.instagram.com/jerakullolli/?__a=1&__d=dis
2025-03-16 01:17:29,843 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jerakullolli/?__a=1&__d=dis) >>> 
2025-03-16 01:17:32,970 - public_request - INFO - [None] [201] GET https://www.instagram.com/jerakullolli/?__a=1&__d=dis
2025-03-16 01:17:32,970 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jerakullolli/?__a=1&__d=dis) >>> 
2025-03-16 01:17:33,971 - instagrapi - INFO - https://i.instagram.com/api/v1/users/jerakullolli/usernameinfo/
2025-03-16 01:17:34,511 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/jerakullolli/usernameinfo/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:17:34,512 - InstagramBot - INFO - Getting followers for user: jerakullolli (ID: 58970943510)
2025-03-16 01:17:35,879 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A%2258970943510%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Afalse%2C%22first%22%3A12%7D&query_hash=37479f2b8209594dde7facb0d904896a
2025-03-16 01:17:35,880 - InstagramBot - INFO - Found 10 followers
2025-03-16 01:17:38,205 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%2260628317391%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
2025-03-16 01:17:43,762 - instagrapi - ERROR - Exceeded 30 redirects.
Traceback (most recent call last):
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 272, in user_info
    user = self.user_info_gql(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 221, in user_info_gql
    return self.user_info_by_username_gql(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 144, in user_info_by_username_gql
    return extract_user_gql(self.public_a1_request(f"/{username!s}/")["user"])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 231, in public_a1_request
    response = self.public_request(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 99, in public_request
    return self._send_public_request(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 152, in _send_public_request
    response = self.public.get(
               ^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
2025-03-16 01:17:44,765 - instagrapi - INFO - https://i.instagram.com/api/v1/users/60628317391/info/
2025-03-16 01:17:45,064 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/60628317391/info/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:17:46,260 - public_request - INFO - [None] [201] GET https://www.instagram.com/albiidr18/?__a=1&__d=dis
2025-03-16 01:17:46,260 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/albiidr18/?__a=1&__d=dis) >>> 
2025-03-16 01:17:49,471 - public_request - INFO - [None] [201] GET https://www.instagram.com/albiidr18/?__a=1&__d=dis
2025-03-16 01:17:49,471 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/albiidr18/?__a=1&__d=dis) >>> 
2025-03-16 01:17:52,698 - public_request - INFO - [None] [201] GET https://www.instagram.com/albiidr18/?__a=1&__d=dis
2025-03-16 01:17:52,698 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/albiidr18/?__a=1&__d=dis) >>> 
2025-03-16 01:17:53,699 - instagrapi - INFO - https://i.instagram.com/api/v1/users/albiidr18/usernameinfo/
2025-03-16 01:18:06,614 - InstagramBot - ERROR - Failed to follow user albiidr18: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/albiidr18/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
2025-03-16 01:18:06,614 - InstagramBot - INFO - Waiting 17.98 seconds before next follow
2025-03-16 01:18:25,921 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%2247873298767%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
2025-03-16 01:18:25,921 - instagrapi - ERROR - 'data'
Traceback (most recent call last):
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 272, in user_info
    user = self.user_info_gql(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 222, in user_info_gql
    self.username_from_user_id_gql(user_id)
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 102, in username_from_user_id_gql
    return self.user_short_gql(user_id).username
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 75, in user_short_gql
    data = self.public_graphql_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 275, in public_graphql_request
    return body_json["data"]
           ~~~~~~~~~^^^^^^^^
KeyError: 'data'
2025-03-16 01:18:26,922 - instagrapi - INFO - https://i.instagram.com/api/v1/users/47873298767/info/
2025-03-16 01:18:27,133 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/47873298767/info/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:18:28,332 - public_request - INFO - [None] [201] GET https://www.instagram.com/grisilda_qosja/?__a=1&__d=dis
2025-03-16 01:18:28,333 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/grisilda_qosja/?__a=1&__d=dis) >>> 
2025-03-16 01:18:31,531 - public_request - INFO - [None] [201] GET https://www.instagram.com/grisilda_qosja/?__a=1&__d=dis
2025-03-16 01:18:31,531 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/grisilda_qosja/?__a=1&__d=dis) >>> 
2025-03-16 01:18:34,736 - public_request - INFO - [None] [201] GET https://www.instagram.com/grisilda_qosja/?__a=1&__d=dis
2025-03-16 01:18:34,737 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/grisilda_qosja/?__a=1&__d=dis) >>> 
2025-03-16 01:18:35,738 - instagrapi - INFO - https://i.instagram.com/api/v1/users/grisilda_qosja/usernameinfo/
2025-03-16 01:18:48,548 - InstagramBot - ERROR - Failed to follow user grisilda_qosja: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/grisilda_qosja/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
2025-03-16 01:18:48,548 - InstagramBot - INFO - Waiting 17.20 seconds before next follow
2025-03-16 01:19:07,087 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%2272847825264%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
2025-03-16 01:19:07,087 - instagrapi - ERROR - 'data'
Traceback (most recent call last):
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 272, in user_info
    user = self.user_info_gql(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 222, in user_info_gql
    self.username_from_user_id_gql(user_id)
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 102, in username_from_user_id_gql
    return self.user_short_gql(user_id).username
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 75, in user_short_gql
    data = self.public_graphql_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 275, in public_graphql_request
    return body_json["data"]
           ~~~~~~~~~^^^^^^^^
KeyError: 'data'
2025-03-16 01:19:08,089 - instagrapi - INFO - https://i.instagram.com/api/v1/users/72847825264/info/
2025-03-16 01:19:08,418 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/72847825264/info/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:19:09,610 - public_request - INFO - [None] [201] GET https://www.instagram.com/veltric_solutions/?__a=1&__d=dis
2025-03-16 01:19:09,611 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/veltric_solutions/?__a=1&__d=dis) >>> 
2025-03-16 01:19:12,817 - public_request - INFO - [None] [201] GET https://www.instagram.com/veltric_solutions/?__a=1&__d=dis
2025-03-16 01:19:12,817 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/veltric_solutions/?__a=1&__d=dis) >>> 
2025-03-16 01:19:16,031 - public_request - INFO - [None] [201] GET https://www.instagram.com/veltric_solutions/?__a=1&__d=dis
2025-03-16 01:19:16,031 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/veltric_solutions/?__a=1&__d=dis) >>> 
2025-03-16 01:19:17,032 - instagrapi - INFO - https://i.instagram.com/api/v1/users/veltric_solutions/usernameinfo/
2025-03-16 01:19:29,825 - InstagramBot - ERROR - Failed to follow user veltric_solutions: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/veltric_solutions/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
2025-03-16 01:19:29,825 - InstagramBot - INFO - Waiting 28.29 seconds before next follow
2025-03-16 01:19:59,719 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%2252171001094%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
2025-03-16 01:19:59,719 - instagrapi - ERROR - 'data'
Traceback (most recent call last):
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 272, in user_info
    user = self.user_info_gql(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 222, in user_info_gql
    self.username_from_user_id_gql(user_id)
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 102, in username_from_user_id_gql
    return self.user_short_gql(user_id).username
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 75, in user_short_gql
    data = self.public_graphql_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 275, in public_graphql_request
    return body_json["data"]
           ~~~~~~~~~^^^^^^^^
KeyError: 'data'
2025-03-16 01:20:00,720 - instagrapi - INFO - https://i.instagram.com/api/v1/users/52171001094/info/
2025-03-16 01:20:00,908 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/52171001094/info/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:20:02,126 - public_request - INFO - [None] [201] GET https://www.instagram.com/careeroffice_beder/?__a=1&__d=dis
2025-03-16 01:20:02,127 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/careeroffice_beder/?__a=1&__d=dis) >>> 
2025-03-16 01:20:05,336 - public_request - INFO - [None] [201] GET https://www.instagram.com/careeroffice_beder/?__a=1&__d=dis
2025-03-16 01:20:05,337 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/careeroffice_beder/?__a=1&__d=dis) >>> 
2025-03-16 01:20:08,543 - public_request - INFO - [None] [201] GET https://www.instagram.com/careeroffice_beder/?__a=1&__d=dis
2025-03-16 01:20:08,544 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/careeroffice_beder/?__a=1&__d=dis) >>> 
2025-03-16 01:20:09,545 - instagrapi - INFO - https://i.instagram.com/api/v1/users/careeroffice_beder/usernameinfo/
2025-03-16 01:20:22,304 - InstagramBot - ERROR - Failed to follow user careeroffice_beder: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/careeroffice_beder/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
2025-03-16 01:20:22,305 - InstagramBot - INFO - Waiting 23.01 seconds before next follow
2025-03-16 01:20:46,532 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%222028746114%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
2025-03-16 01:20:46,532 - instagrapi - ERROR - 'data'
Traceback (most recent call last):
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 272, in user_info
    user = self.user_info_gql(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 222, in user_info_gql
    self.username_from_user_id_gql(user_id)
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 102, in username_from_user_id_gql
    return self.user_short_gql(user_id).username
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 75, in user_short_gql
    data = self.public_graphql_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 275, in public_graphql_request
    return body_json["data"]
           ~~~~~~~~~^^^^^^^^
KeyError: 'data'
2025-03-16 01:20:47,533 - instagrapi - INFO - https://i.instagram.com/api/v1/users/2028746114/info/
2025-03-16 01:20:47,724 - private_request - INFO - veltric_solutions [200] GET https://i.instagram.com/api/v1/users/2028746114/info/ (269.0.0.18.75, OnePlus 6T Dev)
2025-03-16 01:20:48,939 - public_request - INFO - [None] [201] GET https://www.instagram.com/olsishehu/?__a=1&__d=dis
2025-03-16 01:20:48,940 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/olsishehu/?__a=1&__d=dis) >>> 
2025-03-16 01:20:52,169 - public_request - INFO - [None] [201] GET https://www.instagram.com/olsishehu/?__a=1&__d=dis
2025-03-16 01:20:52,169 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/olsishehu/?__a=1&__d=dis) >>> 
2025-03-16 01:20:55,350 - public_request - INFO - [None] [201] GET https://www.instagram.com/olsishehu/?__a=1&__d=dis
2025-03-16 01:20:55,350 - public_request - ERROR - Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/olsishehu/?__a=1&__d=dis) >>> 
2025-03-16 01:20:56,351 - instagrapi - INFO - https://i.instagram.com/api/v1/users/olsishehu/usernameinfo/
2025-03-16 01:21:09,164 - InstagramBot - ERROR - Failed to follow user olsishehu: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/olsishehu/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
2025-03-16 01:21:09,165 - InstagramBot - INFO - Waiting 25.98 seconds before next follow
2025-03-16 01:21:36,375 - public_request - INFO - [None] [200] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%2271674921591%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
2025-03-16 01:21:36,375 - instagrapi - ERROR - 'data'
Traceback (most recent call last):
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 272, in user_info
    user = self.user_info_gql(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 222, in user_info_gql
    self.username_from_user_id_gql(user_id)
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 102, in username_from_user_id_gql
    return self.user_short_gql(user_id).username
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/user.py", line 75, in user_short_gql
    data = self.public_graphql_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albi/Desktop/automationInsta/.venv/lib/python3.12/site-packages/instagrapi/mixins/public.py", line 275, in public_graphql_request
    return body_json["data"]
           ~~~~~~~~~^^^^^^^^
KeyError: 'data'
